
[Commands]

	[Commands.Scessential]

		[Commands.Scessential.Info]

			[Commands.Scessential.Info.GetRegistryName]
				#The searching radius of command /scessential getRegistryName mob to get the registry names of nearby mobs in certain radius
				#The radius is specified here.
				#Default value: 3 blocks (a 7 * 7 * 7 cube)
				#Range: > 1
				Radius = 3

	[Commands.Warp]
		#Set it to false to disable /warp, /setwarp, /delwarp, and /listwarps command.
		#Default value: true
		#This option only work after server restarted.
		IsWarpEnable = true
		#The time interval between two /warp commands, or teleport cooldown, in seconds.
		#Default value: 3 seconds
		#Range: > 0
		WarpCooldown = 3

	[Commands.Fly]
		#Set it to false to disable /fly command.
		#Default value: true,
		#This option only work after server restarted.
		IsFlyEnable = true
		#The date format used to display the deadline of flying.
		#A valid date format should follow the pattern described in JavaDoc: https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
		#If you don't know what it is, please do not modify it.
		#Default value: "hh:mm:ss MM/dd/yyyy"
		DatePattern = "hh:mm:ss MM/dd/yyyy"

	[Commands.TPA]
		#If a tpa request last more than this seconds, that tpa request will be considered expired. 
		#Default value: 60 seconds
		#Range: > 1
		MaxTPARequestExpireTime = 60
		#Set it to false to disable /tpa, /tpahere, /tpaaccept, /tpadeny, /tphere, and /tpallhere command.
		#Default value: true
		#This option only work after server restarted.
		IsTPAEnable = true
		#The time interval between two /tpa and /tpahere commands, or teleport cooldown, in seconds.
		#Default value: 3 seconds
		#Range: > 0
		TPACooldown = 3

	[Commands.Back]
		#The time interval between two /back commands, or teleport cooldown, in seconds.
		#Default value: 3 seconds
		#Range: > 0
		BackCooldown = 3
		#Max amount of times of /back can use to go back to certain locations. 
		#Default value: 10 Times
		#Range: > 1
		MaxBacks = 10
		#Set it to false to disable /back command.
		#Default value: true
		#This option only work after server restarted.
		IsBackEnable = true

	[Commands.Spawn]
		#The time interval between two /spawn commands, or teleport cooldown, in seconds.
		#Default value: 3 seconds
		#Range: > 0
		SpawnCooldown = 3
		#Set it to false to disable /spawn command.
		#Default value: true
		#This option only work after server restarted.
		IsSpawnEnable = true

	[Commands.Home]
		#The time interval between two /homeother commands, or teleport cooldown, in seconds.
		#Default value: 3 seconds
		#Range: > 0
		HomeOtherCooldown = 3
		#Set it to false to disable /home, /sethome, /delhome (/removehome), /listhomes, /homeother, and /listotherhomes command.
		#Default value: true
		#This option only work after server restarted.
		IsSpawnEnable = true
		#The max amount of homes that a player can set.
		#Default value: 5 homes
		#Range: > 1
		MaxHomes = 5
		#The time interval between two /home commands, or teleport cooldown, in seconds.
		#Default value: 3 seconds
		#Range: > 0
		HomeCooldown = 3

	[Commands.RTP]
		#Max attempts for /rtp to find a safe landing site.
		#Default value: 10 Attempts
		#Range: > 1
		MaxRTPAttempts = 10
		#The time interval between two /rtp commands, or teleport cooldown, in seconds.
		#Default value: 10 seconds
		#Range: > 0
		RTPCooldown = 10
		#Set it to false to disable /rtp command.
		#Default value: true
		#This option only work after server restarted.
		IsRTPEnable = true

		[Commands.RTP.TheNetherSettings]
			#The max height in the nether that the /rtp commands could reach.
			#Default value: 100 Blocks
			#Range: 0 ~ 128
			TheNetherMaxHeight = 100
			#The min radius (centered on player) in the nether that the /rtp commands could reach.
			#Default value: 1000 Blocks
			#Range: > 0
			TheNetherMinRadius = 1000
			#The max radius (centered on player) in the nether that the /rtp commands could reach.
			#Default value: 10000 Blocks
			#Range: > 0
			TheNetherMaxRadius = 10000
			#The min height in the nether that the /rtp commands could reach.
			#Default value: 30 Blocks
			#Range: 0 ~ 128
			TheNetherMinHeight = 30

		[Commands.RTP.OverworldSettings]
			#The max radius (centered on player) in overworld that the /rtp commands could reach.
			#Default value: 10000 Blocks
			#Range: > 0
			OverworldMaxRadius = 10000
			#The min radius (centered on player) in overworld that the /rtp commands could reach.
			#Default value: 1000 Blocks
			#Range: > 0
			OverworldMinRadius = 1000
			#The min height in overworld that the /rtp commands could reach.
			#Default value: 1 Blocks
			#Range: 0 ~ 256
			OverworldMinHeight = 1
			#The max height in overworld that the /rtp commands could reach.
			#Default value: 150 Blocks
			#Range: 0 ~ 256
			OverworldMaxHeight = 150

		[Commands.RTP.DefaultSettings]
			#The max radius (centered on player) in any other world that the /rtp commands could reach.
			#Default value: 10000 Blocks
			#Range: > -2147483648
			DefaultMaxRadius = 10000
			#The min height in any other world that the /rtp commands could reach.
			#Default value: 40 Blocks
			#Range: > -2147483648
			DefaultMinHeight = 40
			#The min radius (centered on player) in any other world that the /rtp commands could reach.
			#Default value: 1000 Blocks
			#Range: > -2147483648
			DefaultMinRadius = 1000
			#The max height in any other world that the /rtp commands could reach.
			#Default value: 120 Blocks
			#Range: > -2147483648
			DefaultMaxHeight = 120

		[Commands.RTP.TheEndSettings]
			#The max height in the end that the /rtp commands could reach.
			#Default value: 140 Blocks
			#Range: 0 ~ 256
			TheEndMaxHeight = 140
			#The min height in the end that the /rtp commands could reach.
			#Default value: 40 Blocks
			#Range: 0 ~ 256
			TheEndMinHeight = 40
			#The min radius (centered on player) in the end that the /rtp commands could reach.
			#Default value: 1000 Blocks
			#Range: > 0
			TheEndMinRadius = 1000
			#The max radius (centered on player) in the end that the /rtp commands could reach.
			#Default value: 10000 Blocks
			#Range: > 0
			TheEndMaxRadius = 10000

[EntityCleanup]

	[EntityCleanup.ItemEntities]
		#List of item registry names (E.g: minecraft:stone) not being cleaned.
		#You could use /scessential getItemRegistryName item command with a item hold in your main hand to get it's registry name.
		#You could also use minecraft:* or rats:* to add all items of certain mod to the whitelist.
		ItemEntitiesWhitelist = ["minecraft:diamond", "minecraft:emerald"]
		#Seconds of warning message sent before next action of cleaning item entities.
		#Default value: 30 seconds
		#Range: > 1
		cleanupItemEntitiesCountdown = 30
		#Set it to false to disable cleaning up item entities in your server.
		#Default value: true
		isItemEntityCleanupEnable = true
		#Time interval in seconds between two actions of cleaning item entities.
		#Default value: 300 seconds (5 minutes)
		#Range: > 1
		cleanItemEntitiesInterval = 300

	[EntityCleanup.MobEntities]
		#Seconds of warning message sent before next action of cleaning mob entities.
		#Default value: 30 seconds
		#Range: > 1
		cleanupMobEntitiesCountdown = 30
		#List of mob resourcelocation names (E.g: minecraft:cow) not being cleaned.
		#You could use /scessential getItemRegistryName mob to get the registry names of nearby mobs. (radius specified in Commands section)
		#You could also use minecraft:* or minecolonies:* to add all mobs of certain mod to the whitelist.
		MobEntitiesWhitelist = ["minecraft:cat", "minecraft:mule", "minecraft:wolf", "minecraft:horse", "minecraft:donkey", "minecraft:wither", "minecraft:guardian", "minecraft:villager", "minecraft:iron_golem", "minecraft:snow_golem", "minecraft:vindicator", "minecraft:ender_dragon", "minecraft:elder_guardian"]
		#Set it to false to disable cleaning up mob entities in your server.
		#Default value: true
		isMobEntityCleanupEnable = true
		#Time interval in seconds between two actions of cleaning mob entities.
		#Default value: 360 seconds (6 minutes)
		#Range: > 1
		cleanMobEntitiesInterval = 360

	[EntityCleanup.OtherEntities]
		#Set it to false to disable cleaning up item frame entities in your server.
		#Default value: false
		IsItemFrameEntityCleanupEnable = false
		#Set it to false to disable cleaning up shulker bullet entities in your server.
		#Default value: true
		IsShulkerBulletEntityCleanupEnable = true
		#Set it to false to disable cleaning up firework rocket entities in your server.
		#Default value: false
		IsFireworkRocketEntityCleanupEnable = false
		#Set it to false to disable cleaning up trident entities in your server.
		#Default value: false
		IsTridentEntityCleanupEnable = false
		#Set it to false to disable cleaning up falling block entities in your server.
		#Default value: true
		IsFallingBlocksEntityCleanupEnable = true
		#Set it to false to disable cleaning up boat entities in your server.
		#Default value: false
		IsBoatEntityCleanupEnable = false
		#Time interval in seconds between two actions of cleaning other entities.
		#Default value: 300 seconds (5 minutes)
		#Range: > 1
		cleanOtherEntitiesInterval = 300
		#Set it to false to disable cleaning up arrow entities in your server.
		#Default value: true
		IsArrowEntityCleanupEnable = true
		#Set it to false to disable cleaning up damaging projectile entities (E.g Fireballs and wither skulls) in your server.
		#Default value: false
		IsDamagingProjectileEntityCleanupEnable = false
		#Set it to false to disable cleaning up TNT entities (should be the fired TNT) in your server.
		#Default value: true
		IsTNTEntityCleanupEnable = true
		#Set it to false to disable cleaning up experience orb entities in your server.
		#Default value: true
		IsExperienceOrbEntityCleanupEnable = true
		#Set it to false to disable cleaning up painting entities in your server.
		#Default value: false
		IsPaintingEntityCleanupEnable = false

